[package]
name = "os"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#调用 SBI 服务的接口
log = "0.4"
sbi-rt = {version = "0.0.3",features = ["legacy"]}

[profile.release]
debug = true