[package]
name = "user_lib"  #user目录下的 lib.rs 以及它引用的若干子模块,给代码库取名为user_lib
version = "0.1.0"
authors = ["Yifan Wu <shinbokuow@163.com>"]
edition = "2018"


[dependencies]

[profile.release]
debug = true

# [features]
# board_qemu = []
# board_k210 = []